CREATE TABLE tb_client (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    age INT NOT NULL,
    cpf VARCHAR(14) NOT NULL,
    income DECIMAL(15,2) NOT NULL,
    location VARCHAR(255) NOT NULL
);